version: "3"

services:
  web:
    image: j3ff/puka-web:latest
    build: ./web
    container_name: puka_web
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: puka.j3ff.io
      LETSENCRYPT_HOST: puka.j3ff.io
      LETSENCRYPT_EMAIL: jeff@j3ff.io
    networks:
      - nginxproxy_default
    depends_on:
      - api

  api:
    image: j3ff/puka-api:latest
    build:
      context: ./api
      args:
        port: 80
    container_name: puka_api
    restart: unless-stopped
    environment:
      BASE_URL: "https://puka-api.j3ff.io"
      MONGODB_URI: "mongodb://puka_mongo/puka"
      VIRTUAL_HOST: puka-api.j3ff.io
      LETSENCRYPT_HOST: puka-api.j3ff.io
      LETSENCRYPT_EMAIL: jeff@j3ff.io
    networks:
      - nginxproxy_default
      - private
    depends_on:
      - db

  db:
    image: mongo:3
    container_name: puka_mongo
    restart: unless-stopped
    volumes:
      - /opt/puka/db:/data/db
    networks:
      - private

networks:
  nginxproxy_default:
    external: true
  private: