#!/bin/sh
. config/scripts.sh
webpack-dev-server                       \
  --config $CONFIG_DIR/webpack.config.js \
  --host $DEV_HOST                       \
  --hot                                  \
  --inline                               \
  --content-base "output"                \
  --history-api-fallback
